# Site settings
title: Elicit Behavior
email: 
description: > # this means to ignore newlines until "baseurl:"
  I used to have a blog, I used to write a lot. Now I don't , but I'd like to. So here goes nothing. Also, learning new things is good, so I'm teaching myself Jekyll and Github to build and host this sucker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elicitbehavior.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
